version: 2.1

orbs:
  maven: circleci/maven@0.0.12
jobs:
  build:
    docker:
      - image: "cimg/openjdk:15.0.0"
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - run: java --version
workflows:
  build:
    jobs:
      - build
  #maven_test:
  #  jobs:
  #    - maven/test # checkout, build, test, and upload test results
